:: # Copyright 2013, Big Switch Networks, Inc.
:: #
:: # LoxiGen is licensed under the Eclipse Public License, version 1.0 (EPL), with
:: # the following special exception:
:: #
:: # LOXI Exception
:: #
:: # As a special exception to the terms of the EPL, you may distribute libraries
:: # generated by LoxiGen (LoxiGen Libraries) under the terms of your choice, provided
:: # that copyright and licensing notices generated by LoxiGen are not altered or removed
:: # from the LoxiGen Libraries and the notice provided below is (i) included in
:: # the LoxiGen Libraries, if distributed in source code form and (ii) included in any
:: # documentation for the LoxiGen Libraries, if distributed in binary form.
:: #
:: # Notice: "Copyright 2013, Big Switch Networks, Inc. This library was generated by the LoxiGen Compiler."
:: #
:: # You may not use this file except in compliance with the EPL or LOXI Exception. You may obtain
:: # a copy of the EPL at:
:: #
:: # http://www.eclipse.org/legal/epl-v10.html
:: #
:: # Unless required by applicable law or agreed to in writing, software
:: # distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
:: # WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
:: # EPL for the specific language governing permissions and limitations
:: # under the EPL.
::
void
${data.class_name}_wire_object_id_get(of_object_t *obj, of_object_id_t *id)
{
    unsigned char *buf = OF_OBJECT_BUFFER_INDEX(obj, 0);
    switch (obj->version) {
:: for version, version_data in data.versioned:
    case ${version.constant_version(prefix='OF_VERSION_')}: {
:: m = version_data.discriminator
:: if m.length == 1:
        uint8_t value = *(uint8_t *)(buf + ${m.offset}); /* ${m.name} */
:: elif m.length == 2:
        uint16_t value = U16_NTOH(*(uint16_t *)(buf + ${m.offset})); /* ${m.name} */
:: elif m.length == 4:
        uint32_t value = U32_NTOH(*(uint32_t *)(buf + ${m.offset})); /* ${m.name} */
:: elif m.length == 8:
        uint64_t value = U64_NTOH(*(uint64_t *)(buf + ${m.offset})); /* ${m.name} */
:: else:
:: raise("unsupported parse_wire_types length %d" % m.length)
:: #endif
::
:: # OFDPA_FIXUP start
:: if data.class_name != 'of_oxm_ofdpa':
:: if data.class_name != 'of_oxm_accton':
:: if data.class_name == 'of_oxm':
        if ((value & 0xffff0000) == 0xffff0000) {
            of_oxm_experimenter_wire_object_id_get(obj, id);
            return;
        }
:: #endif
:: # OFDPA_FIXUP end
        switch (value) {
:: for subclass in version_data.subclasses:
        case ${hex(subclass.value)}:
:: if subclass.virtual:
            ${subclass.class_name}_wire_object_id_get(obj, id);
:: else:
            *id = ${subclass.class_name.upper()};
:: #endif
            break;
:: #endfor
        default:
            *id = ${data.class_name.upper()};
            break;
        }
:: # OFDPA_FIXUP start
:: else:
        uint8_t mask = (*(uint8_t *)(buf + 2)) & 0x1; /* oxm_mask */
        if (value == 1) {
            *id = OF_OXM_ACCTON_INPORTS;
        }
        else if (value == 2) {
            *id = OF_OXM_ACCTON_UDF_OFFSET;
        }
        else if (value == 3) {
            if (mask)
                *id = OF_OXM_ACCTON_UDF_DATA_MASKED;
            else
                *id = OF_OXM_ACCTON_UDF_DATA;
        }
        else {
            *id = OF_OXM_ACCTON;
        }
:: #endif
:: else:
        uint8_t mask = (*(uint8_t *)(buf + 2)) & 0x1; /* oxm_mask */
        if (value == 1) {
          *id = OF_OXM_OFDPA_VRF;
        }
        else if (value == 2) {
          *id = OF_OXM_OFDPA_TRAFFIC_CLASS;
        }
        else if (value == 3) {
          *id = OF_OXM_OFDPA_COLOR;
        }
        else if (value == 4) {
          *id = OF_OXM_OFDPA_DEI;
        }
        else if (value == 5) {
          *id = OF_OXM_OFDPA_QOS_INDEX;
        }
        else if (value == 6) {
          *id = OF_OXM_OFDPA_LMEP_ID;
        }
        else if (value == 7) {
          *id = OF_OXM_OFDPA_MPLS_TTL;
        }
        else if (value == 8) {
          if (mask)
              *id = OF_OXM_OFDPA_MPLS_L2_PORT_MASKED;
          else
              *id = OF_OXM_OFDPA_MPLS_L2_PORT;
        }
        else if (value == 9) {
          *id = OF_OXM_OFDPA_L3_IN_PORT;
        }
        else if (value == 10) {
          *id = OF_OXM_OFDPA_OVID;
        }
        else if (value == 11) {
          *id = OF_OXM_OFDPA_MPLS_DATA_FIRST_NIBBLE;
        }
        else if (value == 12) {
          *id = OF_OXM_OFDPA_MPLS_ACH_CHANNEL;
        }
        else if (value == 13) {
          *id = OF_OXM_OFDPA_MPLS_NEXT_LABEL_IS_GAL;
        }
        else if (value == 14) {
          *id = OF_OXM_OFDPA_OAM_Y1731_MDL;
        }
        else if (value == 15) {
          *id = OF_OXM_OFDPA_OAM_Y1731_OPCODE;
        }
        else if (value == 16) {
          *id = OF_OXM_OFDPA_COLOR_ACTIONS_INDEX;
        }
        else if (value == 17) {
          *id = OF_OXM_OFDPA_TXFCL;
        }
        else if (value == 18) {
          *id = OF_OXM_OFDPA_RXFCL;
        }
        else if (value == 19) {
          *id = OF_OXM_OFDPA_RX_TIMESTAMP;
        }
        else if (value == 20) {
          if (mask)
              *id = OF_OXM_OFDPA_BFD_DISCRIMINATOR_MASKED;
          else
              *id = OF_OXM_OFDPA_BFD_DISCRIMINATOR;
        }
        else if (value == 21) {
          *id = OF_OXM_OFDPA_PROTECTION_INDEX;
        }
        else if (value == 22) {
          *id = OF_OXM_OFDPA_BFD_DISCRIMINATOR;
        }
        else if (value == 42) {
          *id = OF_OXM_OFDPA_ACTSET_OUTPUT;
        }
        else {
          *id = OF_OXM_OFDPA;
        }
:: #endif
:: # OFDPA_FIXUP end
        break;
    }
:: #endfor
    default:
        LOCI_ASSERT(0);
    }
}
